### PR TITLE
Add ignore_status

### PR DESCRIPTION
**Pull request by sepich**
Fix for: #160
It seems this option would look better inside of `http_client_config`, but I do not see easy way to extend `HTTPClientConfig` (because it has own `UnmarshalJSON()`)

### CODE REVIEW

**Review by SuperQ — COMMENTED** [review]
I wonder if instead of this, we add something more like the blackbox_exporter's "allowed status codes". This way you can be more explicit about what non-2xx codes are allowed.

**Comment by sepich** [comment]
Yeah, that would also work for us. Fixed.

**Review by SuperQ — APPROVED** [review]
LGTM

**Review by rustycl0ck — APPROVED** [review]
LGTM! Thanks for the PR.

**Pull request merged**
